service: image-service

provider:
  name: aws
  runtime: nodejs6.10

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ]]}
        - "arn:aws:s3:::${self:custom.imageUploaderBucket}/*"

    - Effect: "Allow"
      Action:
        - "states:StartExecution"
      Resource:
        - "*"

custom:
  imageUploaderBucket: test-image-service-new-bucket-test

functions:
  new-image-uploader:
    handler: new-image-uploader/index.upload
    events:
      - http: POST images/upload
    memorySize: 256 # In MB
    environment:
          BUCKET_NAME: ${self:custom.imageUploaderBucket}

  startExecution:
    handler: thumbnail-processor/handler.start
    events:
      - s3:
        bucket: ${self:custom.imageUploaderBucket}
        event: s3:ObjectCreated:*
    environment:
      STATEMACHINE_ARN: ${self:resources.Outputs.ThumbnailProcessor.Value}

  generate-thumbnail:
    handler: thumbnail-processor/handler.generateThumbnail
    environment:
      STATEMACHINE_ARN: ${self:resources.Outputs.ThumbnailProcessor.Value}

stepFunctions:
  stateMachines:
    hellostepfunc1:
      name: thumbnailProcessor
      definition:
        Comment: "StateMachine that turns raw images into thumbnails"
        StartAt: GenerateThumbnail
        States:
          GenerateThumbnail:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-generateThumbnail"
            End: true

resources:
  Resources:
    S3Bucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${self:custom.imageUploaderBucket}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET, PUT, POST, HEAD]
              AllowedOrigins: ['*']
              MaxAge: '3600'
  Outputs:
    ThumbnailProcessor:
      Description: The ARN of the ThumbnailProcessor state machine
      Value:
        Ref: ThumbnailProcessor

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
